### ISSUE TITLE
Should `plotst` use typst's kebab-case casing convention?

### ISSUE THREAD

**Issue by ModProg** [Pegacraft/typst-plotting#3]
Coming from a programming background, snake case feels more natural for myself as well, but due to the typst std using kebab-case, I wonder if it makes sense to also use it in `plotst`. 

I have found my self typing e.g., `graph-plot` or `marking-offset-left` myself multiple times already only to remember that it is snake case.

Don't have a strong feeling about this, just think this should be considered.

**Comment by Pegacraft** [comment]
We have thought about that - the problem is, that it would create issues for backwards compatibility (though not a big one). But it would also mean we'd have to do a 1.\*.\* version, following the rules of the packages repo. And for that, we need more than just a styling case change. But if we do a 1.\*.\* we will consider changing the styling.

~~Typst could change their styling instead~~

**Comment by ModProg** [comment]
> ~Typst could change their styling instead~

I wish :cry:.

> But it would also mean we'd have to do a 1.*.* version, following the rules of the packages repo.

That sounds strange, don't they follow semver? IIRC semver states that `0.*` versions can have breaking changes in minor version bumps.

**Comment by Pegacraft** [comment]
> That sounds strange, don't they follow semver? IIRC semver states that 0.* versions can have breaking changes in minor version bumps.

You are absolutely right - I completely forgot about that part. In that case, we can do the style change in 0.2.0
